### ISSUE TITLE
it doesn't work as expected and it hangs . 

### ISSUE THREAD

**Issue by a-eid** [perrin4869/gulp-html2pug#73]
it doesn't work as expected and it hangs . 

it doesn't convert everything , I keep waiting for it to finish , but it didn't thus far 
![](https://i.imgur.com/rVsjxL1.png)

if I comment the task , pug runs to complete .

**Comment by perrin4869** [comment]
Hi, I need to update the dependencies! Will do this this week, sorry

**Comment by a-eid** [comment]
what dependencies , I will update it my self , 
I need it urgently

thanks

**Comment by a-eid** [comment]
this library `https://github.com/donpark/html2jade`  works perfectly  , but I don't know how to integrate it with `gulp`

**Comment by perrin4869** [comment]
@a-eid Just published version `1.0`, check if it works for you now

**Comment by a-eid** [comment]
Thank you
